# Generated by Django 6.0.6 on 2026-07-21 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='advance_months',
            field=models.PositiveSmallIntegerField(help_text='Maximum 6 months per Section 25(5) of Act 220.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
