# Generated by Django 6.0.6 on 2026-07-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0002_proposal_count_alter_proposal_advance_months'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='count',
            new_name='proposal_count',
        ),
    ]
