# Generated by Django 5.1.15 on 2026-06-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Tenant', 'Tenant'), ('Landlord', 'Landlord'), ('Property_Manager', 'Property Manager'), ('admin', 'System Admin')], default='Tenant', max_length=20),
        ),
    ]
