# Generated by Django 5.1.15 on 2026-06-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord'), ('property_manager', 'Property Manager'), ('admin', 'System Admin')], default='tenant', max_length=20),
        ),
    ]
