[phases.setup]
nixPkgs = ["python312", "gcc", "pkg-config", "gobject-introspection", "glib", "cairo", "pango", "libffi"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "bash start.sh"

