# Generated by Django 5.1.15 on 2026-09-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('rent_card', 'Rent Card'), ('tenancy_agreement', 'Tenancy Agreement'), ('instalment_addendum', 'Instalment Addendum'), ('payment_receipt', 'Payment Receipt'), ('dispute_packet', 'Dispute Packet'), ('default_notice', 'Default Notice')], max_length=32),
        ),
    ]
