# Generated by Django 6.0.6 on 2026-07-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
