# Generated by Django 6.0.6 on 2026-07-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('rent_card', 'Rent Card'), ('tenancy_agreement', 'Tenancy Agreement'), ('instalment_addendum', 'Instalment Addendum')], max_length=32),
        ),
    ]
