# Generated by Django 6.0.6 on 2026-07-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('rent_card', 'Rent Card'), ('tenancy_agreement', 'Tenancy Agreement'), ('instalment_addendum', 'Instalment Addendum'), ('payment_receipt', 'Payment Receipt')], max_length=32),
        ),
    ]
