# Generated by Django 6.0.6 on 2026-08-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('rent_card', 'Rent Card'), ('tenancy_agreement', 'Tenancy Agreement'), ('instalment_addendum', 'Instalment Addendum'), ('payment_receipt', 'Payment Receipt'), ('dispute_packet', 'Dispute Packet')], max_length=32),
        ),
    ]
