# Generated by Django 5.1.15 on 2026-08-29 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordPayoutAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('bank', 'Bank Account'), ('mobile_money', 'Mobile Money')], max_length=16)),
                ('bank_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=150)),
                ('paystack_subaccount_code', models.CharField(blank=True, max_length=100)),
                ('percentage_charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landlord Payout Account',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('move_in', 'Move-in Payment'), ('instalment', 'Instalment Payment')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='pending', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instalment_due_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('paystack_transaction_id', models.CharField(blank=True, max_length=100)),
                ('channel', models.CharField(blank=True, max_length=20)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tenancies.tenancy')),
            ],
            options={
                'verbose_name': 'Payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
