# Generated by Django 5.1.15 on 2026-06-27 15:14

import apps.listings.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='SVG icon name or identifier for display in templates', max_length=50)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in the amenity picker')),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('single_room', 'Single Room'), ('chamber_hall', 'Chamber & Hall'), ('studio', 'Studio'), ('townhouse', 'Townhouse'), ('office', 'Office / Commercial')], max_length=20)),
                ('furnishing_status', models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-Furnished'), ('fully_furnished', 'Fully Furnished')], default='unfurnished', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('rented', 'Rented'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0, help_text='0 for studio / single room', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('bathrooms', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('address', models.CharField(max_length=300)),
                ('neighbourhood', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(default='Accra', max_length=100)),
                ('region', models.CharField(choices=[('Greater Accra', 'Greater Accra'), ('Ashanti', 'Ashanti'), ('Western', 'Western'), ('Eastern', 'Eastern'), ('Central', 'Central'), ('Northern', 'Northern'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('Volta', 'Volta'), ('Savannah', 'Savannah'), ('Brong-Ahafo', 'Brong-Ahafo'), ('Bono East', 'Bono East'), ('Oti', 'Oti'), ('Ahafo', 'Ahafo'), ('Western North', 'Western North'), ('North East', 'North East')], default='Greater Accra', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Decimal degrees. Drop pin on map or enter manually.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Monthly rent in GHC', max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('payment_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Bi-Annual'), ('annual', 'Annual')], default='annual', help_text='How often payment is collected', max_length=15)),
                ('advance_months', models.PositiveSmallIntegerField(default=6, help_text='Advance payment required at move-in. Maximum 6 months per Section 25(5) of Act 220.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, help_text='Refundable security deposit in GHC. 0 if none.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('lease_term_months', models.PositiveSmallIntegerField(default=12, help_text='Total duration of tenancy in months. ', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(240)])),
                ('video_url', models.URLField(blank=True, help_text="Cloudinary video URL — set automatically on upload, don't edit manually.")),
                ('has_instalment_plan', models.BooleanField(default=False, help_text='True when landlord has configured an instalment schedule. Enables the negotiation engine and shows the 📋 badge.')),
                ('available_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='listings.amenity')),
                ('landlord', models.ForeignKey(limit_choices_to={'userprofile__role__in': ['landlord', 'property_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.listings.models._property_photo_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.property')),
            ],
            options={
                'ordering': ['-is_primary', 'display_order'],
            },
        ),
    ]
