# Generated by Django 5.1.15 on 2026-06-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyphoto',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
