# Generated by Django 5.1.15 on 2026-08-31 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyphoto',
            options={'ordering': ['-is_primary']},
        ),
        migrations.RemoveField(
            model_name='property',
            name='security_deposit',
        ),
        migrations.RemoveField(
            model_name='propertyphoto',
            name='display_order',
        ),
    ]
