# Generated by Django 5.1.15 on 2026-06-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, help_text="Cloudinary video URL — set automatically on upload, don't edit manually."),
        ),
    ]
