# Generated by Django 6.0.6 on 2026-07-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_propertyphoto_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('rented', 'Rented'), ('paused', 'Paused'), ('archived', 'Archived'), ('pending_payment', 'Pending Payment')], default='draft', max_length=20),
        ),
    ]
