# Generated by Django 5.1.15 on 2026-06-19 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_property_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lease_term_months',
            field=models.PositiveSmallIntegerField(default=12, help_text='Total duration of tenancy in months. ', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
