# Generated by Django 5.1.15 on 2026-09-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_propertyphoto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('live', 'live'), ('rented', 'Rented'), ('paused', 'Paused'), ('archived', 'Archived'), ('pending_payment', 'Pending Payment'), ('lease_ended', 'Lease Ended')], default='draft', max_length=20),
        ),
    ]
