# Generated by Django 6.0.6 on 2026-07-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyphoto',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Lower numbers appear first in the gallery', null=True),
        ),
    ]
