# Generated by Django 5.1.15 on 2026-06-20 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_property_lease_term_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 for studio / single room', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='lease_term_months',
            field=models.PositiveSmallIntegerField(default=12, help_text='Total duration of tenancy in months. ', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.CharField(choices=[('Greater Accra', 'Greater Accra'), ('Ashanti', 'Ashanti'), ('Western', 'Western'), ('Eastern', 'Eastern'), ('Central', 'Central'), ('Northern', 'Northern'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('Volta', 'Volta'), ('Savannah', 'Savannah')], default='Greater Accra', max_length=100),
        ),
    ]
