# Generated by Django 5.1.15 on 2026-06-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.CharField(choices=[('Greater Accra', 'Greater Accra'), ('Ashanti', 'Ashanti'), ('Western', 'Western'), ('Eastern', 'Eastern'), ('Central', 'Central'), ('Northern', 'Northern'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('Volta', 'Volta'), ('Savannah', 'Savannah'), ('Brong-Ahafo', 'Brong-Ahafo'), ('Bono East', 'Bono East'), ('Oti', 'Oti'), ('Ahafo', 'Ahafo'), ('Western North', 'Western North'), ('North East', 'North East')], default='Greater Accra', max_length=100),
        ),
    ]
