# Generated by Django 6.0.6 on 2026-07-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_property_created_by_property_landlord_reviewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, help_text='SVG icon name or identifier for display in templates', max_length=300),
        ),
    ]
