# Generated by Django 6.0.6 on 2026-07-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_amenity_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, help_text='SVG icon name or identifier for display in templates', max_length=800),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('live', 'live'), ('rented', 'Rented'), ('paused', 'Paused'), ('archived', 'Archived'), ('pending_payment', 'Pending Payment')], default='draft', max_length=20),
        ),
    ]
