# Generated by Django 6.0.6 on 2026-08-12 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerequestmedia',
            old_name='d',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='maintenancerequestmedia',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='maintenance.maintenancerequest'),
        ),
    ]
