# Generated by Django 5.1.15 on 2026-07-03 14:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('listings', '0002_alter_propertyphoto_display_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('expiring', 'Expiring'), ('ended', 'Ended')], default='pending_payment', max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_months', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_card_pdf', models.FileField(blank=True, upload_to='rent_cards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tenancy', to='applications.application')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies_as_landlord', to=settings.AUTH_USER_MODEL)),
                ('rental_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='listings.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies_as_tenant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenancy',
                'verbose_name_plural': 'Tenancies',
                'ordering': ['-created_at'],
            },
        ),
    ]
