# Generated by Django 6.0.6 on 2026-07-09 21:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenancy',
            name='rent_card_pdf',
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='status',
            field=models.CharField(choices=[('pending_negotiation', 'Pending Negotiation'), ('pending_agreement', 'Pending Agreement'), ('pending_payment', 'Pending Payment'), ('active', 'Active'), ('expiring', 'Expiring'), ('ended', 'Ended')], default='pending_negotiation', max_length=20),
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_landlord', 'Pending Landlord Confirmation'), ('pending_tenant', 'Pending Tenant Confirmation'), ('fully_executed', 'Fully Executed')], default='pending_landlord', max_length=20)),
                ('special_conditions_raw', models.TextField(blank=True)),
                ('special_conditions', models.TextField(blank=True)),
                ('landlord_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('landlord_otp_ref', models.CharField(blank=True, max_length=100)),
                ('tenant_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_otp_ref', models.CharField(blank=True, max_length=100)),
                ('fully_executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agreement', to='tenancies.tenancy')),
            ],
            options={
                'verbose_name': 'Agreement',
            },
        ),
    ]
