# Generated by Django 6.0.6 on 2026-07-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancies', '0002_remove_tenancy_rent_card_pdf_alter_tenancy_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='status',
            field=models.CharField(choices=[('pending_negotiation', 'Pending Negotiation'), ('pending_agreement', 'Pending Agreement'), ('pending_payment', 'Pending Payment'), ('active', 'Active'), ('expiring', 'Expiring'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='pending_negotiation', max_length=20),
        ),
    ]
